logs_pipeline:
  source:
    otel_logs_source:
      port: 4317
      ssl: false
  sink:
    - opensearch:
        hosts: [ "http://persistence-opensearch.persistence:9200" ]
        index_type: custom
        index: otel-events-%{yyyy.MM.dd}
        bulk_size: 4

metrics_pipeline:
  source:
    otel_metrics_source:
      port: 4318
      ssl: false
  processor:
    - otel_metrics_raw_processor:
        calculate_histogram_buckets: true
        calculate_exponential_histogram_buckets: true
        exponential_histogram_max_allowed_scale: 10
        flatten_attributes: false
  sink:
    - opensearch:
        hosts: [ "http://persistence-opensearch.persistence:9200" ]
        index_type: custom
        template_type: index-template
        template_file: "/usr/share/data-prepper/pipelines/ss4o_metrics.json"
        index: ss4o_metrics-otel-%{yyyy.MM.dd}
        bulk_size: 4

traces_pipeline:
  source:
    otel_trace_source:
      port: 4319
      ssl: false
  sink:
    - pipeline:
        name: "raw_traces_pipeline"
    - pipeline:
        name: "service_traces_pipeline"

raw_traces_pipeline:
  source:
    pipeline:
      name: "traces_pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: ["http://persistence-opensearch.persistence:9200"]
        insecure: true
        index_type: trace-analytics-raw
        trace_analytics_raw: true

service_traces_pipeline:
  source:
    pipeline:
      name: "traces_pipeline"
  processor:
    - service_map_stateful:
  sink:
    - opensearch:
        hosts: ["http://persistence-opensearch.persistence:9200"]
        insecure: true
        index_type: trace-analytics-service-map
        trace_analytics_service_map: true
