logs_pipeline:
  source:
    otel_logs_source:
      port: 4317
      ssl: false
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        index: logs-otel-v1-%{yyyy.MM.dd}

metrics_pipeline:
  source:
    otel_metrics_source:
      port: 4318
      ssl: false
  processor:
    - otel_metrics_raw_processor:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        index: metrics-otel-v1-%{yyyy.MM.dd}

traces_pipeline:
  source:
    otel_trace_source:
      port: 4319
      ssl: false
  sink:
    - pipeline:
        name: "raw_traces_pipeline"
    - pipeline:
        name: "service_traces_pipeline"

raw_traces_pipeline:
  source:
    pipeline:
      name: "traces_pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: trace-analytics-raw
        trace_analytics_raw: true

service_traces_pipeline:
  source:
    pipeline:
      name: "traces_pipeline"
  processor:
    - service_map:
  sink:
    - opensearch:
        hosts: ["http://opensearch:9200"]
        insecure: true
        index_type: trace-analytics-service-map
        trace_analytics_service_map: true
