metrics_pipeline:
  source:
    otel_metrics_source:
      port: 4318
      unframed_requests: true
      proto_reflection_service: true
      ssl: false
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        index: metrics-otel-v1-%{yyyy.MM.dd}

logs_pipeline:
  source:
    otel_logs_source:
      port: 4317
      unframed_requests: true
      proto_reflection_service: true
      ssl: false
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        index: logs-otel-v1-%{yyyy.MM.dd}

traces_pipeline:
  source:
    otel_trace_source:
      port: 4319
      unframed_requests: true
      proto_reflection_service: true
      ssl: false
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        index: traces-otel-v1-%{yyyy.MM.dd}