apiVersion: v2
name: persistence
description: A overall chart for releases of all infrastructure of Berte project

version: 0.1.1

dependencies:
  - name: postgres
    version: 0.1.0
    repository: file://charts/postgres
    condition: postgres.enabled

  - name: keydb
    version: 0.1.0
    repository: file://charts/keydb
    condition: keydb.enabled

  - name: zookeeper
    version: 0.1.0
    repository: file://charts/zookeeper
    condition: zookeeper.enabled

  - name: kafka
    version: 0.1.0
    repository: file://charts/kafka
    condition: kafka.enabled

  - name: schema-registry
    version: 0.1.0
    repository: file://charts/schema-registry
    condition: schema-registry.enabled

  - name: clickhouse
    version: 0.1.0
    repository: file://charts/clickhouse
    condition: clickhouse.enabled

  - name: opensearch
    version: 0.1.0
    repository: file://charts/opensearch
    condition: opensearch.enabled
