global:
  serviceDiscoveryRoleBinding: true
  env:
    TEST_ENV: "TEST"

postgres:
  enabled: true
  image:
    repository: "postgres"
    tag: "16.3"
  resources:
    requests:
      memory: 256Mi
      cpu: 20m
    limits:
      memory: 384Mi
      cpu: 300m
  env:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test