apiVersion: v2
name: business
description: A overall chart for releases of all monitoring infrastructure of Berte project

version: 0.1.0

dependencies:
  - name: auth
    version: 0.1.0
    repository: file://charts/auth
    condition: auth.enabled