apiVersion: v2
name: ui
description: A overall chart for releases of all ui infrastructure of Berte project

version: 0.1.0

dependencies:
  - name: kafka-ui
    version: 0.1.0
    repository: file://charts/kafka-ui
    condition: kafka-ui.enabled
  - name: opensearch-dashboard
    version: 0.1.0
    repository: file://charts/opensearch-dashboard
    condition: opensearch-dashboard.enabled
  - name: pgadmin
    version: 0.1.0
    repository: file://charts/pgadmin
    condition: pgadmin.enabled
