scrape_configs:
  - job_name: 'sample_monitoring'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus'
    basic_auth:
      username: 'user'
      password: 'password'
    static_configs:
      - targets: ['service:8080']